%% 
% all lengths are in micrometer
NA=1.38; % numerical aperture
ri=1.515;% refractive index of immersion oil
lambda=.5; % emission vacuum wavelength
kxmax=NA/lambda; % radius of bfp for oil immersion objective
s=[256 256]; % image size
cosTheta=newim(s)+1;                  
kz_of_kxky=cosTheta;

klen=ri/lambda; % radius of ewald sphere

kx=xx(s,'freq')*4*kxmax;
ky=yy(s,'freq')*4*kxmax;              

tmp2=klen^2-(kx.^2+ky.^2);  
aperture=tmp2>0; % only the cap of the ewald sphere contributes
cosTheta(aperture)=sqrt(tmp2(aperture));        
                    % Theta, being the angle to the optic axis
kz_of_kxky=cosTheta;
%% prepare phase to propagate to different slices of the stack
nz=13; % number of slices
dz=lambda/(2*(ri-sqrt(ri^2-NA^2))); % step size in um
z=xx(nz,'corner')*dz; % defocus in um
sxy=1/(2*kxmax); % um per pixel
vol=[s nz];
fpropmat=newim(vol,'dcomplex');
for i=0:length(z)-1
    fpropmat(:,:,i)=exp(kz_of_kxky(:,:)*(1i*klen/sxy*z(i)));
end
%% spot width for lcos and mma
rl=.1; 
rm=.1;
%% define either smooth or b/w lcos image
%lcos=exp(-rr(s,'freq').^2/(rl/2)^2)
lcos=rr(s,'freq')<rl/2
%% define either smooth or b/w mma image
mma=exp(-((xx(s,'freq')-.2/2).^2 + (yy(s,'freq')-.3/2).^2)/(rm/2)^2);
%mma=((xx(s,'freq')-.2/2).^2 + (yy(s,'freq')-.3/2).^2)<(rm/2)^2;
overlay(255*mma,~aperture)

%% spot size of mma in k-space, the smaller the mma, the less illumination
%% angles are needed for the incoherent image
rmk=2/(s(1)*pi*rm);
abs(ft(mma))/max(abs(ft(mma)))-exp(-rr(s,'freq').^2/rmk^2);
rmk_pixels=rmk*256;
%% reduce sampling of lcos image according to spot size generated by mma
%% aperture, illuminate pixels that contribute with 3% to the result
ill_mask=resample(lcos,[1/rmk_pixels 1/rmk_pixels],[0 0])>.03;
% kx must have kxmax on the border
ill_kx=xx(ill_mask,'freq')*rmk_pixels;
ill_ky=yy(ill_mask,'freq')*rmk_pixels;

%% parallel coherent illumination
vol=[s nz];
coh=newim(vol,'dcomplex');
current=ft(ft(mma).*lcos).*aperture;
for i=0:nz-1
    coh(:,:,i)=abs(ft(current.*squeeze(fpropmat(:,:,i)))).^2;
end
clear current

%% incoherent illumination
incoh=newim(vol,'dfloat');
bfp=newim(s,'dcomplex');
[row col]=size(ill);
count=0;
all=sum(ill_mask);
for j=0:row-1
    for i=0:col-1
        if ill_mask(i,j)
            shifter=exp(1i*(ill_kx(i,j)*xx(s)+ill_ky(i,j)*yy(s)));
            bfp=ft(ft(mma.*shifter).*lcos).*aperture;
            for k=0:nz-1
                incoh(:,:,k)=squeeze(incoh(:,:,k))+...
                    abs(ft(bfp.*squeeze(fpropmat(:,:,k)))).^2;
            end
            count=count+1;
            [count all]
        end
    end
end
clear bfp;

%% compare gauss and sharp edged mma hole
comp=reshape(dincoh/max(dincoh)-gincoh/max(gincoh),[256 256*nz]);
out=255*(comp-min(comp))/(max(comp)-min(comp));
writeim(out,'/home/martin/1031/memi/disk-gauss-big.jpg','JPEG');
%%
mosaic=[reshape(incoh,[256 256*nz]) reshape(gincoh,[256 256*nz]) ...
    reshape(dincoh,[256 256*nz])];
out=255*(mosaic-min(mosaic))/(max(mosaic)-min(mosaic));
writeim(out,...
    '/home/martin/1031/memi/mgauss-ldisk_mgauss-lgauss_mdisk-lgauss_big.jpg'...
    ,'JPEG');
